fix: don't throw on older versions of Node.js 6 (#711)
The `url.URL` object was added in Node.js v6.13.0. If you tried to
perform a `foo instanceof url.URL` on earlier versions, the code would
throw the following exception:

TypeError: Expecting a function in instanceof check, but got undefined